apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/kumar-neok-gmail-com/hello-neok:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/kumar-neok-gmail-com/hello-neok:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: hello-neok
        chartPath: charts/hello-neok
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/kumar-neok-gmail-com/hello-neok"
          image.tag: "{{.DIGEST_HEX}}"
